# Generated by Django 5.1.5 on 2025-02-05 11:08

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="portfolio/")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Project Name")),
                ("client", models.CharField(max_length=255)),
                (
                    "rating",
                    models.CharField(
                        choices=[("T", "Top"), ("N", "Normal")],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("web_url", models.URLField(blank=True, null=True)),
                ("images", models.ImageField(upload_to="portfolio/")),
                ("log_images", models.ImageField(upload_to="portfolio/")),
                ("top_images", models.ImageField(upload_to="portfolio/")),
                ("dashboard_images", models.ImageField(upload_to="portfolio/")),
                ("nav_images", models.ImageField(upload_to="portfolio/")),
                ("description", models.TextField(blank=True, null=True)),
                ("deployment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
                (
                    "backend_technologies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="backend_technologies",
                        to="core.technology",
                    ),
                ),
                (
                    "database_technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_technology",
                        to="core.technology",
                    ),
                ),
                (
                    "frontend_technologies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="frontend_technologies",
                        to="core.technology",
                    ),
                ),
                (
                    "other_technologies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="other_technologies",
                        to="core.technology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created_at"],
            },
        ),
    ]
