# Generated by Django 5.1.5 on 2025-02-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="section",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="section",
            field=models.ManyToManyField(to="core.section"),
        ),
    ]
