# Generated by Django 5.1.5 on 2025-02-05 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_options_alter_technology_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="reading_time",
        ),
    ]
