# Generated by Django 5.1.5 on 2025-02-06 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_portfolio_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("whatsapp", models.URLField(max_length=100)),
                ("twitter_link", models.URLField(max_length=100)),
                ("linkedin", models.URLField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Company Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Company Description"
                    ),
                ),
                (
                    "company_story",
                    models.TextField(
                        blank=True, null=True, verbose_name="Company Story"
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        choices=[
                            ("Development", "Development"),
                            ("Design", "Design"),
                            ("Hosting", "Hosting"),
                            ("Other", "Other"),
                        ],
                        default="Development",
                        max_length=200,
                        verbose_name="Main Service",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Address",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "technologies_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="technologies",
                        to="core.technology",
                        verbose_name="Technologies Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
    ]
