# Generated by Django 5.1.5 on 2025-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_team_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="github",
            field=models.URLField(
                default="https://github.com/Ali-Sina-255/", max_length=100
            ),
            preserve_default=False,
        ),
    ]
