# Generated by Django 5.1.2 on 2025-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_gallerycategory_alter_images_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/about", verbose_name="About Images "
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
    ]
